<?php

/**
 * @file
 * Contains webform_user_create.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function webform_user_create_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the webform_user_create module.
    case 'help.page.webform_user_create':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Webform User Create adds a handler to Webform that will create a new user based on field values.') . '</p>';
      return $output;

    default:
  }
}
