module:
  address: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  config_direct_save: 0
  contact: 0
  contextual: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  encrypt: 0
  entity: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  geocoder: 0
  geocoder_address: 0
  geocoder_field: 0
  geolocation: 0
  help: 0
  history: 0
  image: 0
  inline_form_errors: 0
  key: 0
  libraries: 0
  link: 0
  mailchimp: 0
  menu_ui: 0
  migrate: 0
  migrate_drupal: 0
  migrate_drupal_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  profile: 0
  quickedit: 0
  rdf: 0
  real_aes: 0
  search: 0
  shortcut: 0
  simple_block: 0
  social_media_links: 0
  social_media_links_field: 0
  stripe: 0
  stripe_webform: 0
  system: 0
  taxonomy: 0
  taxonomy_manager: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_ui: 0
  webform: 0
  webform_encrypt: 0
  webform_examples: 0
  webform_mailchimp: 0
  webform_templates: 0
  webform_ui: 0
  webform_user_create: 0
  webform_views: 0
  webform_wizard_full_title: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  realm: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
