<?php

/**
 * Implements hook_preprocess_breadcrumb().
 */
function realm_preprocess_breadcrumb(array &$variables) {
  // Set the cache tag.
  $variables['#cache']['contexts'][] = 'url.path';

  // Get the page title and add to the end of the breadcrumb.
  $request = \Drupal::request();
  $route = \Drupal::routeMatch()->getRouteObject();
  $page_title = \Drupal::service('title_resolver')
    ->getTitle($request, $route);

  $variables['breadcrumb'][] = array(
    'text' => $page_title
  );
}